// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutApp: typeof import('./components/AboutApp.vue')['default']
    AppInstall: typeof import('./components/AppInstall.vue')['default']
    BackgroundBocca: typeof import('./components/BackgroundBocca.vue')['default']
    Bulbulian: typeof import('./components/svg/Bulbulian.vue')['default']
    FamLogo: typeof import('./components/svg/FamLogo.vue')['default']
    GameControllers: typeof import('./components/GameControllers.vue')['default']
    NavPersonPages: typeof import('./components/NavPersonPages.vue')['default']
    PersonBubble: typeof import('./components/PersonBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNav: typeof import('./components/TopNav.vue')['default']
    TopNavPeople: typeof import('./components/TopNavPeople.vue')['default']
    YouTube: typeof import('./components/YouTube.vue')['default']
  }
}
