// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutApp: typeof import('./components/AboutApp.vue')['default']
    AppInstall: typeof import('./components/AppInstall.vue')['default']
    BackgroundBocca: typeof import('./components/BackgroundBocca.vue')['default']
    Bulbulian: typeof import('./components/svg/Bulbulian.vue')['default']
    ControllerLutris: typeof import('./components/controllers/ControllerLutris.vue')['default']
    ControllerPS3: typeof import('./components/controllers/ControllerPS3.vue')['default']
    ControllerPS3guitar: typeof import('./components/controllers/ControllerPS3guitar.vue')['default']
    ControllerPS3move: typeof import('./components/controllers/ControllerPS3move.vue')['default']
    ControllerSNES: typeof import('./components/controllers/ControllerSNES.vue')['default']
    FamilyTree: typeof import('./components/homePage/FamilyTree.vue')['default']
    FamLogo: typeof import('./components/svg/FamLogo.vue')['default']
    GameControllers: typeof import('./components/controllers/GameControllers.vue')['default']
    GamePlayHistory: typeof import('./components/homePage/GamePlayHistory.vue')['default']
    GoogleLogin: typeof import('./components/GoogleLogin.vue')['default']
    NavPersonPages: typeof import('./components/NavPersonPages.vue')['default']
    NewMovies: typeof import('./components/homePage/NewMovies.vue')['default']
    PersonBubble: typeof import('./components/PersonBubble.vue')['default']
    PersonBubbleAmira: typeof import('./components/PersonBubblePerPerson/PersonBubbleAmira.vue')['default']
    PersonBubbleBen: typeof import('./components/PersonBubblePerPerson/PersonBubbleBen.vue')['default']
    PersonBubbleChris: typeof import('./components/PersonBubblePerPerson/PersonBubbleChris.vue')['default']
    PersonBubbleMarc: typeof import('./components/PersonBubblePerPerson/PersonBubbleMarc.vue')['default']
    PersonBubbleMel: typeof import('./components/PersonBubblePerPerson/PersonBubbleMel.vue')['default']
    PersonBubbleRoger: typeof import('./components/PersonBubblePerPerson/PersonBubbleRoger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNav: typeof import('./components/TopNav.vue')['default']
    TopNavNotifications: typeof import('./components/TopNavNotifications.vue')['default']
    TopNavPeople: typeof import('./components/TopNavPeople.vue')['default']
    WildWaterKingdom: typeof import('./components/homePage/WildWaterKingdom.vue')['default']
    YouTube: typeof import('./components/YouTube.vue')['default']
  }
}
